export const MASTER_QUESTIONS = [
  {
    id: 1,
    domain: "attention",
    level: 1,
    title: "Temukan Kartu yang berbeda",
    href: "/attention/1",
  },
  {
    id: 2,
    domain: "attention",
    level: 2,
    title: "Perhatikan urutan warna 1-3",
    href: "/attention/2",
  },
  {
    id: 3,
    domain: "attention",
    level: 3,
    title: "Perhatikan urutan warna 1-4",
    href: "/attention/3",
  },
  {
    id: 4,
    domain: "motoric",
    level: 1,
    title: "ketuk angka 1-4",
    href: "/motoric/1",
  },
  {
    id: 5,
    domain: "motoric",
    level: 2,
    title: "Ketuk angka 1-6",
    href: "/motoric/2",
  },
  {
    id: 6,
    domain: "motoric",
    level: 3,
    title: "Ketuk lingkaran sebelum menghilang",
    href: "/motoric/3",
  },
  {
    id: 7,
    domain: "communication",
    level: 1,
    title: "Mana Yang apel",
    href: "/communication/1",
  },
  {
    id: 8,
    domain: "communication",
    level: 2,
    title: "Lengkapi Kalimat berikut (Kucing suka minum)",
    href: "/communication/2",
  },
  {
    id: 9,
    domain: "communication",
    level: 3,
    title: "Susun kata Menjadi kalimat yang benar",
    href: "/communication/3",
  },
  {
    id: 10,
    domain: "sensory",
    level: 1,
    title: "apa warna yang datang selanjutnya",
    href: "/sensory/1",
  },
  {
    id: 11,
    domain: "sensory",
    level: 2,
    title: "angka berikutnya adalah",
    href: "/sensory/2",
  },
  {
    id: 12,
    domain: "sensory",
    level: 3,
    title: "apa yang warna akan datang selanjutnya",
    href: "/sensory/3",
  },
  {
    id: 13,
    domain: "social",
    level: 1,
    title: "apa perasaan anak ini",
    href: "/social/1",
  },
  {
    id: 14,
    domain: "social",
    level: 2,
    title: "Temanmu menangis karna jatuh apa yang kamu lakukan",
    href: "/social/2",
  },
  {
    id: 15,
    domain: "social",
    level: 3,
    title:
      "ditaman bermain kamu melihat anak baru terlihat kesepian dan tidak bermain bersama siapapun apa yang kamu lakukan",
    href: "/social/3",
  },
];
